# Part of the Crubit project, under the Apache License v2.0 with LLVM
# Exceptions. See /LICENSE for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

[package]
name = "ir"
edition = "2021"

[lib]
path = "../../ir.rs"

[dependencies]
flagset = "0.4"
once_cell = "1"
proc-macro2 = "1"
quote = "1"
serde = { version = "1", features = ["derive", "rc"] }
serde_json = "1"
arc_anyhow = { path = "../../../common/cargo/arc_anyhow" }
code_gen_utils = { path = "../../../common/cargo/code_gen_utils" }
