# Part of the Crubit project, under the Apache License v2.0 with LLVM
# Exceptions. See /LICENSE for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

[package]
name = "code_gen_utils"
edition = "2021"

[lib]
path = "../../code_gen_utils.rs"

[dependencies]
once_cell = "1"
itertools = "0.13"
proc-macro2 = "1"
syn = "2"
quote = "1"
unicode-ident = "1"
arc_anyhow = { path = "../../../common/cargo/arc_anyhow" }
